# CircleCI configuration file

version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Check installed versions
          command: |
            docker -v
            docker-compose -v
      - run:
          name: Build base images
          command: |
            make -j10 build
      - run:
          name: Show all built images
          command: |
            docker image ls | sort
      - run:
          name: Show all source images
          command: |
            grep -Rh ^FROM | grep -v { | sort -u
      - run:
          name: Show image tag cross reference
          command: |
            cat build.txt
            
workflows:
  version: 2
  commit:
    jobs:
      - build
